sserghei23/Skeleton

Testing1/tstOrder.cs

Testing functionality after deleting local folder

---

AdminSystem/StaffManagementDataEntry.aspx
Testing2/TestingStaffManagement.csproj
Testing2/clsStaff.cs
Testing2/tstStaff.cs

Added testing for staff class

---

Skeleton.sln
Testing4/UnitTest1.cs
Testing4/tstCustomer.csproj

Made a tests class

---

ClassLibrary/clsOrder.cs
Testing1/tstOrder.cs

Properties have been created an all the tests passed

Created Properties

---

AdminSystem/OrderManagementDataEntry.aspx
AdminSystem/OrderManagementDataEntry.aspx.cs
AdminSystem/OrderManagementViewer.aspx.cs
Skeleton.sln

Added labels text boxes and buttons

Presentation

---

AdminSystem/OrderManagementViewer.aspx.cs
ClassLibrary/clsOrder.cs
Skeleton.sln
Testing1/tstOrder.cs

All the tests have passed successfully

Created Find methods for all the properties

---

AdminSystem/OrderManagementDataEntry.aspx
AdminSystem/OrderManagementDataEntry.aspx.cs
AdminSystem/OrderManagementViewer.aspx.cs
ClassLibrary/clsOrder.cs
Testing1/tstOrder.cs

Modified the tests and method to work with the property values from the database table. also added a find button when executed it populates the text fields with the values of the properties.

Modified the find method to work with database connection

---

AdminSystem/CustomerManagementConfirmDelete.aspx
AdminSystem/CustomerManagementDataEntry.aspx
AdminSystem/CustomerManagementDataEntry.aspx.cs
AdminSystem/CustomerManagementViewer.aspx.cs
AdminSystem/OrderManagementDataEntry.aspx.cs
Skeleton.sln

Adding Middle Layers to data

---

AdminSystem/CustomerManagementDataEntry.aspx
AdminSystem/CustomerManagementDataEntry.aspx.cs
AdminSystem/CustomerManagementViewer.aspx.cs
ClassLibrary/clsCustomer.cs
SQLQuery1.sql
Testing4/tstCustomer.cs

Creating Mind method - (Middle Layer) and (Individual)

Creating Mind method - (Middle Layer) and (Individual)

---

AdminSystem/OrderManagementDataEntry.aspx.cs
ClassLibrary/clsOrder.cs
Testing1/tstOrder.cs

All the validation tests passed

Added validation to database properties

---

AdminSystem/OrderManagementDataEntry.aspx.cs
AdminSystem/OrderManagementViewer.aspx
AdminSystem/OrderManagementViewer.aspx.cs
ClassLibrary/clsOrder.cs

i added validation so that it shows an error and the details of the error. I also added a button in the viewer to go back.

added validation in the presentation layer. 

---

AdminSystem/CustomerManagementDataEntry.aspx
AdminSystem/CustomerManagementDataEntry.aspx.cs
AdminSystem/CustomerManagementViewer.aspx.cs
AdminSystem/OrderManagementDataEntry.aspx.cs
ClassLibrary/clsCustomer.cs
SQLQuery4.sql
Testing4/tstCustomer.cs

lab 9b - Creating the Find Method - Middle Layer

lab 9b - Creating the Find Method - Middle Layer

---

AdminSystem/StaffManagementDataEntry.aspx
AdminSystem/StaffManagementDataEntry.aspx.cs
ClassLibrary/clsStaff.cs
Testing2/tstStaff.cs

Successfully managed to initialise data from the staff management database into the data entry form.

Completed the Middle Layer for Staff Management

---

ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsInventory.cs
Testing5/TestingInventoryManagement.csproj
Testing5/tstInventory.cs

Added the initial test methods for my component Inventory Management1

created a test class for inventory management! and updated clsInventory

---

AdminSystem/OrderManagementList.aspx
AdminSystem/OrderManagementList.aspx.cs
ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsOrderCollection.cs
Testing1/TestingOrderManagement.csproj
Testing1/tstOrderCollection.cs

created some tests for the new class. also added a list web form and populated it with data from the database.

added a new collection class and properties to it.

---

AdminSystem/StaffManagementList.aspx
AdminSystem/StaffManagementList.aspx.cs
ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsStaff.cs
ClassLibrary/clsStaffCollection.cs
Testing2/TestingStaffManagement.csproj
Testing2/tstStaff.cs
Testing2/tstStaffCollection.cs

Completed Lab 12, implemented collection class, updated the StaffManagement viewer page, run all test methods successfully.

Creating the Collection Class for StaffManagement

---

AdminSystem/OrderManagementDataEntry.aspx.cs
AdminSystem/OrderManagementList.aspx
AdminSystem/OrderManagementList.aspx.cs
ClassLibrary/clsOrderCollection.cs
Testing1/tstOrderCollection.cs

all the tests made passed successfully and the methods work as they should

added add and edit methods

---

AdminSystem/CustomerManagementDataEntry.aspx.cs
AdminSystem/CustomerManagementList.aspx
AdminSystem/CustomerManagementList.aspx.cs
ClassLibrary/ClassLibrary.csproj
ClassLibrary/clsCustomerCollection.cs
Testing4/TestingCustomerManagement.csproj
Testing4/tstCustomer.cs
Testing4/tstCustomerCollection.cs

Creating Collections

---

AdminSystem/OrderManagementConfirmDelete.aspx
AdminSystem/OrderManagementConfirmDelete.aspx.cs
AdminSystem/OrderManagementList.aspx
AdminSystem/OrderManagementList.aspx.cs
ClassLibrary/clsOrderCollection.cs
Testing1/tstOrderCollection.cs

Created unit tests for the filter and delete method and all of them pass successfully, also created the filter and delete methods and they work properly

added a delete and filter method

---

AdminSystem/OrderManagementList.aspx
AdminSystem/OrderManagementList.aspx.cs
AdminSystem/OrderManagementStatistics.aspx
AdminSystem/OrderManagementStatistics.aspx.cs
ClassLibrary/clsOrder.cs
Testing1/TestingOrderManagement.csproj
Testing1/tstOrder.cs
Testing1/tstOrderCollection.cs

created stored procedures that can generate statistics and then added to a grid view on the new page.

added a new statistics web page

---

AdminSystem/CheckoutManagementList.aspx
AdminSystem/CheckoutManagementList.aspx.cs
AdminSystem/CustomerManagementDataEntry.aspx.cs
ClassLibrary/clsCustomer.cs
ClassLibrary/clsCustomerCollection.cs
Testing4/tstCustomer.cs
Testing4/tstCustomerCollection.cs

Creating the Collection Class Methods - " The Add Method"

Creating the Collection Class Methods - " The Add Method"

---

AdminSystem/StaffManagementDataEntry.aspx
AdminSystem/StaffManagementDataEntry.aspx.cs
AdminSystem/StaffManagementList.aspx
AdminSystem/StaffManagementList.aspx.cs
ClassLibrary/clsStaffCollection.cs
Testing2/tstStaff.cs
Testing2/tstStaffCollection.cs

Implementing the Add and Edit Methods for Staff Management

---

AdminSystem/CustomerManagementDataEntry.aspx
AdminSystem/CustomerManagementDataEntry.aspx.cs
AdminSystem/CustomerManagementList.aspx
AdminSystem/CustomerManagementList.aspx.cs
ClassLibrary/clsCustomerCollection.cs
Testing4/tstCustomer.cs
Testing4/tstCustomerCollection.cs

Creating the Collection Class Methods - The Edit Method

Creating the Collection Class Methods - The Edit Method

---

AdminSystem/CustomerManagementConfirmDelete.aspx
AdminSystem/CustomerManagementConfirmDelete.aspx.cs
AdminSystem/CustomerManagementDataEntry.aspx
AdminSystem/CustomerManagementDataEntry.aspx.cs
AdminSystem/CustomerManagementList.aspx
AdminSystem/CustomerManagementList.aspx.cs
ClassLibrary/clsCustomer.cs
ClassLibrary/clsCustomerCollection.cs
Testing4/tstCustomer.cs
Testing4/tstCustomerCollection.cs

Practical 14 a - Creating the method "Delete Button"

Practical 14 a - Creating the method "Delete Button"

---

AdminSystem/OrderManagementConfirmDelete.aspx
AdminSystem/OrderManagementDataEntry.aspx
AdminSystem/OrderManagementList.aspx
AdminSystem/OrderManagementStatistics.aspx
AdminSystem/TeamMainMenu.aspx
Testing1/tstOrder.cs

Added bootstrap and gave my pages a modern look. also made a change to two of my test methods

fully implemented bootstrap

---

AdminSystem/OrderManagementConfirmDelete.aspx
AdminSystem/OrderManagementDataEntry.aspx
AdminSystem/OrderManagementList.aspx
AdminSystem/OrderManagementStatistics.aspx
AdminSystem/TeamMainMenu.aspx
Testing1/tstOrder.cs

Made bootstrap changes and fixed one of the test methods

made some visual changes

---

AdminSystem/CustomerManagementDataEntry.aspx
AdminSystem/CustomerManagementDataEntry.aspx.cs
AdminSystem/CustomerManagementList.aspx
AdminSystem/CustomerManagementList.aspx.cs
AdminSystem/CustomerManagementStatistics.aspx
AdminSystem/CustomerManagementStatistics.aspx.cs
AdminSystem/CustomerManagementViewer.aspx
AdminSystem/CustomerManagementViewer.aspx.cs
AdminSystem/TeamMainMenu.aspx
AdminSystem/TeamMainMenu.aspx.cs
ClassLibrary/clsCustomer.cs
ClassLibrary/clsCustomerCollection.cs
Testing4/tstCustomer.cs
Testing4/tstCustomerCollection.cs

Newest Update
